[package]
name = "actix_htpasswd"
version = "0.1.0"
authors = ["Thomas BAGREL <tomsb07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
base64 = "0.11"
sha-1 = "0.8"
futures = "0.3"

